node0: &node
  build: ./target/docker/stage
  environment:
    APP_ADDR: 192.168.42.41
    APP_PORT: 2551
    BIND_APP_PORT: 2552
    SEED_NODES: 192.168.42.41:2551
  ports:
    - "2551:2552"
  volumes:
    - ./target/shared-journal:/opt/docker/target/shared-journal
    - ./target/shared-snapshots:/opt/docker/target/shared-snapshots

node1:
  <<: *node
  environment:
    APP_ADDR: 192.168.42.41
    APP_PORT: 2552
    BIND_APP_PORT: 2552
    SEED_NODES: 192.168.42.41:2551
  ports:
    - "2552:2552"
  volumes:
    - ./target/shared-journal:/opt/docker/target/shared-journal
    - ./target/shared-snapshots:/opt/docker/target/shared-snapshots
  links:
    - node0
