node0: &node
  build: ./target/docker/stage
  environment:
    APP_ADDR: ${THING}
    APP_PORT: 2551
    BIND_APP_PORT: 2551
    SEED_NODES: 127.0.0.1:2551
  ports:
    - "2551:2551"
  net: "host"
  volumes:
    - /tmp/shared-journal:/tmp/shared-journal
    - /tmp/shared-snapshots:/tmp/shared-snapshots

node1:
  <<: *node
  environment:
    APP_PORT: 2552
    BIND_APP_PORT: 2552
    SEED_NODES: 127.0.0.1:2551
  ports:
    - "2552:2552"
  net: "host"
  volumes:
    - /tmp/shared-journal:/tmp/shared-journal
    - /tmp/shared-snapshots:/tmp/shared-snapshots
